In [1]:
from borsdata_client import BorsdataClient
client = BorsdataClient()
dfs = client.history_kpi(66,'Large Cap', 'Sverige')

Atlas Copco A
AAKAstraZeneca

Biotage
Nordnet
Intrum
Kinnevik B
Addtech
Autoliv
Beijer Ref
Alfa Laval
ABB
Fabege
Millicom
Bilia
Hexpol
Assa Abloy
Sandvik
Bure Equity
SEB A
Atrium Ljungberg
Holmen B
Axfood
Securitas
New Wave
Lagercrantz
HMS Networks
Industrivärden C
Orrön Energy
Mycronic
Sagax A
Addnode
Catena
Modern Times Group B
Avanza Bank
Sectra
Diös Fastigheter
Peab
Lundbergföretagen
JM
Billerud
Boliden
Wallenstam
Volati
Loomis
Electrolux B
Investor B
Bravida
Latour
Fastpartner A
Thule
Cint GroupAtlas Copco B
Fortnox
Sweco A

Medicover
Lindab
Embracer
Vitec Software
Instalco
AFRYHemnet
Tele2 A
NP3 Fastigheter Pref
Trelleborg

Truecaller
Storskogen
NCAB Group
Investor A
Essity A
Husqvarna A
Volvo Car
Sdiptech Pref
Traton
SSAB B
Husqvarna B
Epiroc A
Holmen A
Skanska
Creades
Ratos B
Kinnevik A
Kindred
Sagax B
Corem Property B
NP3 Fastigheter
Telia Company
Arjo
Sampo
Volvo A
Ericsson A
TietoEVRY
Hexagon
SKF B
Arion Banki
Lundin Mining
Viaplay B
OX2
Systemair
Saab
Byggfakta
Electrolux A
SSAB A
Electrolux Professional B
Industrivärden A
Bufab
Sinch
Stora Enso R
Hennes & Mauritz
Mips
Swedish Orphan Biovitrum
EQT
Indutrade
Nokia
Volvo B
SKF A
Essity B
Sdiptech
Munters
NCC B
Ericsson B
Troax Group
Samhällsbyggnadsbolag B
Tele2 B
Getinge
Fast Balder
Platzer Fastigheter
Handelsbanken B
Vitrolife
Samhällsbyggnadsbolag D
SCA A
SCA B
Stora Enso A
Corem Property Pref
NCC A
Lundin Gold
International Petroleum
AddLife
Wihlborgs Fastigheter
Swedbank
Modern Times Group A
Stillfront
Nordea Bank
Viaplay A
Epiroc B
Nyfosa
Alleima
Sweco B
Nolato
Boozt
Corem Property D
Sagax D
Ratos A
Fenix Outdoor
SEB C
NIBE Industrier
Hufvudstaden A
Pandox
Fastpartner D
Evolution
Dometic
Elekta
Corem Property A
Lifco
Castellum
Hexatronic
Volati Pref
Handelsbanken A
BioArctic

In [8]:
import pandas as pd
frames = pd.concat(dfs)
frames[frames.name == 'Addnode']

    year  period  kpiValue     name
0   2013       3     0.563  Addnode
1   2013       4     0.563  Addnode
2   2014       1     0.563  Addnode
3   2014       2     0.563  Addnode
4   2014       3     0.563  Addnode
5   2014       4     0.563  Addnode
6   2015       1     0.563  Addnode
7   2015       2     0.563  Addnode
8   2015       3     0.563  Addnode
9   2015       4     0.563  Addnode
10  2016       1     0.563  Addnode
11  2016       2     0.563  Addnode
12  2016       3     0.563  Addnode
13  2016       4     0.563  Addnode
14  2017       1     0.563  Addnode
15  2017       2     0.563  Addnode
16  2017       3     0.563  Addnode
17  2017       4     0.563  Addnode
18  2018       1     0.563  Addnode
19  2018       2     0.563  Addnode
20  2018       3     0.563  Addnode
21  2018       4     0.625  Addnode
22  2019       1     0.625  Addnode
23  2019       2     0.625  Addnode
24  2019       3     0.625  Addnode
25  2019       4     0.000  Addnode
26  2020       1     0.000  Addnode
27  2020       2     0.000  Addnode
28  2020       3     0.000  Addnode
29  2020       4     0.625  Addnode
30  2021       1     0.625  Addnode
31  2021       2     0.625  Addnode
32  2021       3     0.625  Addnode
33  2021       4     0.750  Addnode
34  2022       1     0.750  Addnode
35  2022       2     0.750  Addnode
36  2022       3     0.750  Addnode
37  2022       4     1.000  Addnode
38  2023       1     1.000  Addnode
39  2023       2     1.000  Addnode